homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 25
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customizations

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  server_port: 8123
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  #ssl_certificate: /home/pi/ssl/chain
  #ssl_key: /home/pi/ssl/key

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 30
  icon: mdi:home

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
    - google_cast
    - denonavr

homekit:
  pincode: !secret homekitpin

# Prometheus
prometheus:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# Components:
group: !include groups.yaml
light: !include lights.yaml
media_player: !include  media_player.yaml
device_tracker: !include device_tracker.yaml
emulated_hue: !include emulated_hue.yaml
sensor: !include_dir_list sensors
scene: !include_dir_list scenes